import { type DequeueResult, type EnqueueInput, type QueueAdapter, type QueueBackendKind, type QueueJobRecord, type QueueJobStatus, type QueueStats, type RedisQueueConfig } from "./queue-adapter-types.js";
export declare class RedisQueueAdapter implements QueueAdapter {
    private readonly config;
    readonly backendKind: QueueBackendKind;
    private readonly client;
    private readonly jobTtlSeconds;
    constructor(config: RedisQueueConfig);
    private jobKey;
    private waitingKey;
    private activeKey;
    private completedKey;
    private deadLetterKey;
    private queueSetKey;
    enqueue(input: EnqueueInput): QueueJobRecord;
    dequeue(_queueName: string): DequeueResult | null;
    getJob(_jobId: string): QueueJobRecord | null;
    listJobs(_queueName: string, _status?: QueueJobStatus, _limit?: number): QueueJobRecord[];
    moveToDeadLetter(_jobId: string, _reason: string): void;
    retryJob(_jobId: string): QueueJobRecord | null;
    purge(_queueName: string, _olderThan: string): number;
    stats(_queueName: string): QueueStats;
    listQueues(): string[];
    private unsupported;
    enqueueAsync(input: EnqueueInput): Promise<QueueJobRecord>;
    dequeueAsync(queueName: string): Promise<DequeueResult | null>;
    getJobAsync(jobId: string): Promise<QueueJobRecord | null>;
    private mapRedisToJobRecord;
    listJobsAsync(queueName: string, status?: QueueJobStatus, limit?: number): Promise<QueueJobRecord[]>;
    moveToDeadLetterAsync(jobId: string, reason: string): Promise<void>;
    retryJobAsync(jobId: string): Promise<QueueJobRecord | null>;
    purgeAsync(queueName: string, olderThan: string): Promise<number>;
    statsAsync(queueName: string): Promise<QueueStats>;
    listQueuesAsync(): Promise<string[]>;
    ping(): Promise<string>;
    close(): Promise<void>;
}
