/**
 * Errors Integration Tests
 *
 * Tests cross-cutting error handling and AppError interoperability
 * with other contract modules.
 */

import test from "node:test";
import assert from "node:assert/strict";

import { AppError, ValidationError, PolicyDeniedError, AuthError, ProviderError,
         createErrorCode, isAppError, getErrorCode, normalizeToAppError } from "../../../../src/platform/contracts/errors.js";
import {
  createPrincipalRef,
  createTaskDraft,
  createConfirmedTaskSpec,
  createRequestEnvelopeFromConfirmedTask,
  createHarnessRun,
  createPlanGraphBundle,
  createNodeRun,
  createNodeAttempt,
  createNodeAttemptReceipt,
  createBudgetLedger,
  createBudgetReservation,
  reserveBudgetHardCap,
} from "../../../../src/platform/contracts/executable-contracts/index.js";
import { createOperationalDirective, createDecisionDirective } from "../../../../src/platform/contracts/control-directive/index.js";
import { createStateCommand } from "../../../../src/platform/contracts/state-command/index.js";

// =============================================================================
// AppError Serialization/Deserialization Cross-Contract Tests
// =============================================================================

test("integration: AppError serializes correctly and can be detected after crossing module boundaries", () => {
  const err = new ValidationError("VAL_CODE", "Validation failed in request envelope", {
    statusCode: 400,
    traceId: "trace-123",
    taskId: "task-456",
  });

  const json = err.toJSON();

  // Simulate passing through JSON boundary (network, storage, etc.)
  const reconstructed = JSON.parse(JSON.stringify(json));

  // Verify reconstruction
  assert.equal(reconstructed.code, "VAL_CODE");
  assert.equal(reconstructed.statusCode, 400);
  assert.equal(reconstructed.traceId, "trace-123");
  assert.equal(reconstructed.taskId, "task-456");
  assert.equal(reconstructed.category, "validation");
});

test("integration: AppError subclass hierarchy is preserved after normalization", () => {
  const originalProviderError = new ProviderError("PROV_FAIL", "Provider unavailable");

  // Simulate cross-system handoff where error might get wrapped
  const normalized = normalizeToAppError(originalProviderError, {
    code: "FALLBACK",
    message: "Something went wrong"
  });

  // ProviderError should be preserved through normalization since it's already an AppError
  assert.equal(normalized.code, "PROV_FAIL");
  assert.equal(normalized.category, "provider");
  assert.equal(normalized.retryable, true);
});

test("integration: Error codes generated by createErrorCode work with ValidationError", () => {
  const code = createErrorCode("V", 1);
  const err = new ValidationError(code, "Test validation error");

  // The code should be properly formatted
  assert.equal(err.code, "EV001");
  assert.ok(err.code.startsWith("E"));
});

test("integration: getErrorCode works across contract module boundaries", () => {
  const errors = [
    new AppError("APP001", "App error"),
    new ValidationError("VAL001", "Validation error"),
    new PolicyDeniedError("POL001", "Policy denied"),
    new AuthError("AUTH001", "Auth failed"),
  ];

  for (const err of errors) {
    assert.equal(getErrorCode(err), err.code);
    assert.ok(isAppError(err));
  }
});

test("integration: getErrorCode returns fallback for non-AppError from other modules", () => {
  const originalError = new Error("Original error from external module");

  // This simulates an error thrown by a dependency that isn't converted
  const fallbackCode = getErrorCode(originalError);

  assert.equal(fallbackCode, "E0000");
});

// =============================================================================
// Error Handling in Contract Lifecycle Tests
// =============================================================================

test("integration: ValidationError thrown during budget operation is properly typed", () => {
  const ledger = createBudgetLedger({
    tenantId: "tenant-1",
    harnessRunId: "hrun-val-1",
    currency: "USD",
    hardCap: 100,
  });

  // Reserve some budget
  const result1 = reserveBudgetHardCap({
    ledger,
    amount: 30,
    resourceKind: "token",
    expiresAt: "2026-04-30T00:00:00.000Z",
    expectedVersion: ledger.version,
  });

  assert.equal(result1.ledger.reservedAmount, 30);

  // Try to exceed cap
  let caughtError: unknown = null;
  try {
    reserveBudgetHardCap({
      ledger: result1.ledger,
      amount: 100,  // Exceeds remaining 70
      resourceKind: "token",
      expiresAt: "2026-04-30T00:00:00.000Z",
      expectedVersion: result1.ledger.version,
    });
  } catch (error) {
    caughtError = error;
  }

  // The error should be an AppError subclass
  assert.ok(caughtError instanceof AppError);
  assert.equal(caughtError.category, "validation");
  assert.equal(caughtError.code, "budget_reservation.hard_cap_exceeded");
});

test("integration: Version mismatch during budget reservation produces AppError", () => {
  const ledger = createBudgetLedger({
    tenantId: "tenant-1",
    harnessRunId: "hrun-version-1",
    currency: "USD",
    hardCap: 100,
  });

  // Try to reserve with wrong version
  let caughtError: unknown = null;
  try {
    reserveBudgetHardCap({
      ledger,
      amount: 50,
      resourceKind: "token",
      expiresAt: "2026-04-30T00:00:00.000Z",
      expectedVersion: 99,  // wrong version
    });
  } catch (error) {
    caughtError = error;
  }

  assert.ok(caughtError instanceof AppError);
  assert.equal(caughtError.category, "validation");
});

test("integration: State command validation errors are properly typed", () => {
  const principal = createPrincipalRef({
    principalId: "user-1",
    tenantId: "tenant-1",
    roles: [],
  });

  let caughtError: unknown = null;

  try {
    createStateCommand({
      entityKind: "",  // Empty should fail
      entityId: "task-1",
      action: "upsert",
      expectedVersion: null,
      payload: {},
      emittedBy: "worker-1",
    });
  } catch (error) {
    caughtError = error;
  }

  assert.ok(caughtError instanceof AppError);
  assert.ok(caughtError instanceof ValidationError);
});

// =============================================================================
// Error Propagation Through Directive Creation
// =============================================================================

test("integration: Directive creation with empty type produces ValidationError", () => {
  const issuedBy = {
    principalId: "user-1",
    tenantId: "tenant-1",
    roles: ["operator"] as const,
  };

  let caughtError: unknown = null;

  try {
    createOperationalDirective({
      type: "" as any,
      issuedBy,
      reason: "test",
    });
  } catch (error) {
    caughtError = error;
  }

  assert.ok(caughtError instanceof AppError);
  assert.equal(caughtError.category, "validation");
});

test("integration: Decision directive with empty targetRef produces ValidationError", () => {
  const issuedBy = {
    principalId: "user-1",
    tenantId: "tenant-1",
    roles: ["operator"] as const,
  };

  let caughtError: unknown = null;

  try {
    createDecisionDirective({
      type: "approve",
      issuedBy,
      targetRef: "",
      payload: {},
      reason: "test",
    });
  } catch (error) {
    caughtError = error;
  }

  assert.ok(caughtError instanceof AppError);
  assert.equal(caughtError.category, "validation");
});

// =============================================================================
// Error Recovery and Continuation Tests
// =============================================================================

test("integration: AppError.wrap returns same instance for AppError (no double-wrapping)", () => {
  const original = new ProviderError("ORIGINAL", "Original provider error");

  // Wrap the error with additional context
  const wrapped = AppError.wrap(original, "WRAPPED", "Wrapped with context", {
    taskId: "task-recovery-1",
  });

  // AppError.wrap returns same instance when wrapping an AppError (no double-wrapping)
  assert.strictEqual(wrapped, original);
  assert.equal(wrapped.code, "ORIGINAL");  // Original code preserved
  assert.equal(wrapped.taskId, null);  // Original taskId preserved (not overwritten)
});

test("integration: AppError.wrap creates new wrapper for non-AppError errors", () => {
  const original = new Error("Original error from external module");

  // Wrap a non-AppError
  const wrapped = AppError.wrap(original, "WRAPPED", "Wrapped with context", {
    taskId: "task-recovery-1",
  });

  // Should create new AppError instance
  assert.notStrictEqual(wrapped, original);
  assert.equal(wrapped.code, "WRAPPED");
  assert.equal(wrapped.taskId, "task-recovery-1");
  assert.ok(wrapped.internalDetails !== null);
  assert.ok("originalError" in wrapped.internalDetails);
});

test("integration: Budget hard cap throws ValidationError when exceeded", () => {
  const ledger = createBudgetLedger({
    tenantId: "tenant-1",
    harnessRunId: "hrun-recover",
    currency: "USD",
    hardCap: 100,
  });

  // Reserve some budget
  const result = reserveBudgetHardCap({
    ledger,
    amount: 50,
    resourceKind: "token",
    expiresAt: "2026-04-30T00:00:00.000Z",
    expectedVersion: ledger.version,
  });

  assert.equal(result.ledger.reservedAmount, 50);
  assert.equal(result.ledger.status, "active");

  // Now try to exceed cap - should throw
  let caughtError: unknown = null;
  try {
    reserveBudgetHardCap({
      ledger: result.ledger,
      amount: 200,  // Exceeds cap
      resourceKind: "token",
      expiresAt: "2026-04-30T00:00:00.000Z",
      expectedVersion: result.ledger.version,
    });
  } catch (error) {
    caughtError = error;
  }

  // Error should be an AppError subclass
  assert.ok(caughtError instanceof AppError);
  assert.equal(caughtError.category, "validation");
  assert.equal(caughtError.code, "budget_reservation.hard_cap_exceeded");
});

// =============================================================================
// Error Context Propagation Tests
// =============================================================================

test("integration: Error context propagates through plan graph creation", () => {
  const principal = createPrincipalRef({
    principalId: "user-1",
    tenantId: "tenant-1",
    roles: ["operator"],
  });

  const riskPreview = {
    riskClass: "high" as const,
    reasons: ["External API call"],
  };

  const confirmedSpec = createConfirmedTaskSpec({
    taskDraftId: "draft-error-1",
    tenantId: "tenant-1",
    principal,
    goal: "Call external API",
    inputs: {},
    constraintPackRef: "cp-error-1",
    riskClass: "high",
    idempotencyKey: "idem-error-1",
    traceId: "trace-error-1",
  });

  const envelope = createRequestEnvelopeFromConfirmedTask({
    confirmedTaskSpec: confirmedSpec,
    budgetIntent: { amount: 100, currency: "USD", resourceKinds: ["token", "api"] },
  });

  const run = createHarnessRun({
    tenantId: envelope.tenantId,
    confirmedTaskSpecId: envelope.confirmedTaskSpecId,
    requestEnvelopeId: envelope.requestId,
    requestHash: envelope.requestHash,
    constraintPackRef: envelope.constraintPackRef,
    versionLockId: "vl-error-1",
    budgetLedgerId: "bledger-error-1",
  });

  const graph = {
    graphId: "graph-error-1",
    nodes: [{
      nodeId: "node-error-1",
      nodeType: "tool" as const,
      inputRefs: [],
      outputSchemaRef: "schema://output",
      riskClass: "high" as const,
      budgetIntent: { amount: 50, currency: "USD", resourceKinds: ["api"] },
      sideEffectProfile: { mayCommitExternalEffect: true, reversible: false },
      retryPolicyRef: "retry://default",
      timeoutMs: 30000,
    }],
    edges: [],
    entryNodeIds: ["node-error-1"],
    terminalNodeIds: ["node-error-1"],
    joinStrategy: "all" as const,
    graphHash: "hash-error-1",
  };

  const bundle = createPlanGraphBundle({
    harnessRunId: run.harnessRunId,
    graph,
    schedulerPolicy: { policyId: "scheduler-error", strategy: "priority_then_fifo" },
    budgetPlanRef: "budget-plan-error",
    riskProfile: riskPreview,
  });

  assert.ok(bundle.planGraphBundleId.startsWith("pgb_"));
  assert.equal(bundle.graph.nodes[0].riskClass, "high");
});

test("integration: Multiple error types can be distinguished in batch processing", () => {
  const errors = [
    new ValidationError("E1", "Validation 1"),
    new PolicyDeniedError("E2", "Policy 1"),
    new AuthError("E3", "Auth 1"),
    new ProviderError("E4", "Provider 1"),
  ];

  const categories = errors.map(e => e.category);
  const retryable = errors.map(e => e.retryable);

  assert.deepEqual(categories, ["validation", "policy", "auth", "provider"]);
  assert.deepEqual(retryable, [false, false, false, true]);  // ProviderError is retryable
});

test("integration: AppError.toJSON produces both camelCase and snake_case for API compatibility", () => {
  const err = new AppError("API_ERR", "API Error message", {
    statusCode: 422,
    category: "validation",
    source: "gateway",
    traceId: "trace-api",
    taskId: "task-api",
  });

  const json = err.toJSON();

  // Both camelCase and snake_case should be present
  assert.equal(json.code, "API_ERR");
  assert.equal(json.userMessage, "API Error message");
  assert.equal(json.user_message, "API Error message");
  assert.equal(json.traceId, "trace-api");
  assert.equal(json.trace_id, "trace-api");
  assert.equal(json.taskId, "task-api");
  assert.equal(json.task_id, "task-api");
  assert.equal(json.statusCode, 422);
});