export * from "./api/index.js";
export * from "./console/index.js";
export * from "./workers/index.js";
export type { PlatformAppManifest } from "../platform-architecture-types.js";
import type { PlatformAppKind, PlatformAppManifest, PlatformStartupTarget, PlatformStartupTargetKind } from "../platform-architecture-types.js";
export declare function listPlatformApps(): readonly PlatformAppManifest[];
export declare function listPlatformAppKinds(): readonly PlatformAppKind[];
export declare function getPlatformAppManifestByKind(kind: PlatformAppKind): PlatformAppManifest;
export declare function resolvePlatformAppManifest(selector: PlatformAppKind | string): PlatformAppManifest | null;
export declare function buildPlatformStartupTargets(): readonly PlatformStartupTarget[];
export declare function resolvePlatformStartupTarget(targetKind: PlatformStartupTargetKind): PlatformStartupTarget;
