export {
  assemblePromptSegments,
  DEFAULT_ML_CLASSIFIER_CONFIG,
  classifyPromptInjectionRisk,
  embedCanaryToken,
  detectCanaryTokenLeakage,
  executePromptDefenseChain,
  classifyRiskLevel,
  protectSystemPrompt,
  inspectProtectedModelOutput,
  sanitizePromptInput,
  sanitizePromptOutput,
  type CanaryTokenResult,
  type PromptDefenseLayer,
  type PromptDefenseLayerAssessment,
  type PromptDefenseIntegration,
  type MLInjectionClassifierConfig,
  type PromptInjectionClassification,
  type PromptInjectionSignal,
  type PromptRoleSegment,
  type PromptProtectionInspection,
  type PromptProtectionPlan,
} from "../shared/stability/prompt-injection-guard.js";
