import test from "node:test";
import assert from "node:assert/strict";
import {
  DEFAULT_SINGLE_TASK_MAX_RETRIES,
  DEFAULT_SINGLE_TASK_RETRY_BACKOFF,
  DEFAULT_RUNTIME_BACKPRESSURE_HEALTH_OPTIONS,
  createContext,
  type HappyPathInput,
} from "../../../../src/platform/five-plane-execution/execution-engine/single-task-happy-path-support.js";

test("DEFAULT_SINGLE_TASK_MAX_RETRIES is 2 [single-task-happy-path-support]", () => {
  assert.equal(DEFAULT_SINGLE_TASK_MAX_RETRIES, 2);
});

test("DEFAULT_SINGLE_TASK_RETRY_BACKOFF is linear [single-task-happy-path-support]", () => {
  assert.equal(DEFAULT_SINGLE_TASK_RETRY_BACKOFF, "linear");
});

test("DEFAULT_RUNTIME_BACKPRESSURE_HEALTH_OPTIONS has correct defaults [single-task-happy-path-support]", () => {
  assert.equal(DEFAULT_RUNTIME_BACKPRESSURE_HEALTH_OPTIONS.memoryHighWatermarkMb, Number.POSITIVE_INFINITY);
  assert.equal(DEFAULT_RUNTIME_BACKPRESSURE_HEALTH_OPTIONS.eventLoopLagThresholdMs, Number.POSITIVE_INFINITY);
  assert.equal(DEFAULT_RUNTIME_BACKPRESSURE_HEALTH_OPTIONS.tier1AckDegradedThreshold, 100);
});

test("HappyPathInput structure with all fields [single-task-happy-path-support]", () => {
  const input: HappyPathInput = {
    dbPath: "/tmp/test.db",
    title: "Test Task",
    request: "Do something",
    tenantId: "tenant_123",
    admissionPolicy: { maxConcurrent: 10 },
    admissionBackpressureSnapshot: () => null,
    crashInjection: { mode: "none" },
    stepOutputOverride: { key: "value" },
    logger: { log: (_level, _msg) => undefined },
  };

  assert.equal(input.dbPath, "/tmp/test.db");
  assert.equal(input.title, "Test Task");
  assert.equal(input.request, "Do something");
  assert.equal(input.tenantId, "tenant_123");
  assert.equal(input.admissionPolicy?.maxConcurrent, 10);
  assert.equal(typeof input.admissionBackpressureSnapshot, "function");
  assert.equal(input.crashInjection?.mode, "none");
  assert.deepEqual(input.stepOutputOverride, { key: "value" });
  assert.equal(typeof input.logger?.log, "function");
});

test("HappyPathInput structure with minimal fields [single-task-happy-path-support]", () => {
  const input: HappyPathInput = {
    dbPath: "/tmp/test.db",
    title: "Minimal Task",
    request: "Do minimal thing",
  };

  assert.equal(input.dbPath, "/tmp/test.db");
  assert.equal(input.title, "Minimal Task");
  assert.equal(input.tenantId, undefined);
  assert.equal(input.admissionPolicy, undefined);
  assert.equal(input.crashInjection, undefined);
});

test("createContext builds TransitionAuditContext from root trace [single-task-happy-path-support]", () => {
  const rootTrace = {
    traceId: "trace_root_123",
    spanId: "span_parent_123",
    correlationId: "corr_789",
  };

  const result = createContext(rootTrace, "TEST_REASON");

  assert.equal(result.reasonCode, "TEST_REASON");
  assert.equal(result.traceId, "trace_root_123");
  // parentSpanId comes from createChildTraceContext which sets parentSpanId = parent.spanId ?? null
  // Since rootTrace has spanId, parentSpanId will be set to that value
  assert.equal(result.parentSpanId, "span_parent_123");
  // spanId is newly generated by createChildTraceContext (not the same as input)
  assert.ok(result.spanId != null);
  assert.notEqual(result.spanId, "span_parent_123");
  assert.equal(result.correlationId, "corr_789");
  assert.equal(result.actorType, "system");
  assert.ok(result.occurredAt != null);
});

test("createContext handles missing optional trace fields [single-task-happy-path-support]", () => {
  const rootTrace = {
    traceId: "trace_simple",
    spanId: undefined,
  };

  const result = createContext(rootTrace as any, "REASON_X");

  assert.equal(result.reasonCode, "REASON_X");
  assert.equal(result.traceId, "trace_simple");
  // When rootTrace has no spanId, parentSpanId is null
  assert.equal(result.parentSpanId, null);
  // spanId is generated
  assert.ok(result.spanId != null);
  // correlationId falls back to traceId
  assert.equal(result.correlationId, "trace_simple");
});

test("createContext generates valid ISO timestamp [single-task-happy-path-support]", () => {
  const rootTrace = {
    traceId: "trace_time_test",
    parentSpanId: null,
  };

  const before = Date.now();
  const result = createContext(rootTrace as any, "TIME_TEST");
  const after = Date.now();

  // occurredAt should be a valid ISO string
  assert.ok(result.occurredAt != null);
  const timestamp = new Date(result.occurredAt).getTime();
  assert.ok(timestamp >= before && timestamp <= after);
});
