apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: automatic-agent-pod-kill
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app.kubernetes.io/name: automatic-agent
  duration: "30s"
