import { z } from "zod";
export declare const LearningObjectSchema: z.ZodObject<{
    learningObjectId: z.ZodString;
    learningType: z.ZodEnum<["failure_pattern", "user_correction", "recovery_playbook"]>;
    title: z.ZodString;
    summary: z.ZodString;
    confidence: z.ZodNumber;
    evidenceRefs: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    sourceSignalIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    recommendation: z.ZodString;
    validatedBy: z.ZodDefault<z.ZodEnum<["none", "evidence", "human_review", "shadow_execution"]>>;
    promotionStatus: z.ZodDefault<z.ZodEnum<["draft", "validated", "promoted", "retired"]>>;
    createdAt: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    summary: string;
    createdAt: number;
    title: string;
    confidence: number;
    learningObjectId: string;
    learningType: "failure_pattern" | "user_correction" | "recovery_playbook";
    recommendation: string;
    evidenceRefs: string[];
    sourceSignalIds: string[];
    validatedBy: "none" | "human_review" | "evidence" | "shadow_execution";
    promotionStatus: "draft" | "retired" | "validated" | "promoted";
}, {
    summary: string;
    createdAt: number;
    title: string;
    confidence: number;
    learningObjectId: string;
    learningType: "failure_pattern" | "user_correction" | "recovery_playbook";
    recommendation: string;
    evidenceRefs?: string[] | undefined;
    sourceSignalIds?: string[] | undefined;
    validatedBy?: "none" | "human_review" | "evidence" | "shadow_execution" | undefined;
    promotionStatus?: "draft" | "retired" | "validated" | "promoted" | undefined;
}>;
export type LearningObject = z.infer<typeof LearningObjectSchema>;
export declare function parseLearningObject(input: unknown): LearningObject;
