export const INTAKE_INTENT_CONFIDENCE_THRESHOLD = 0.8;
export const INTAKE_DISAMBIGUATION_THRESHOLD = 0.8;
export const INTAKE_LOW_CONFIDENCE_THRESHOLD = 0.5;
export const INTAKE_SLOT_CONFIDENCE_THRESHOLD = 0.85;
