/**
 * @fileoverview Edit Replacement Matching - Core matching algorithms.
 *
 * Multi-stage matching algorithm that progressively relaxes matching criteria:
 * 1. exact - literal string match
 * 2. whitespace_normalized - ignores spaces/tabs, trims lines
 * 3. indentation_normalized - normalizes indentation levels
 * 4. fuzzy - Dice coefficient similarity (threshold: 85%)
 * 5. context_anchored - fuzzy match within before/after anchor region
 */
/**
 * Internal structure representing a potential match candidate.
 */
export interface MatchCandidate {
    /** Start byte offset in the content */
    startOffset: number;
    /** End byte offset in the content */
    endOffset: number;
    /** The text content of this candidate */
    text: string;
}
/**
 * Internal structure for match outcome at a given attempt level.
 */
export interface MatchOutcome {
    /** Whether a unique match was found */
    matched: boolean;
    /** Number of candidates found */
    candidateCount: number;
    /** The matched candidate if exactly one found; null otherwise */
    candidate: MatchCandidate | null;
    /** Similarity score for fuzzy matches; null for exact matches */
    similarityScore: number | null;
    /** Warning codes generated during matching */
    warningCodes: string[];
    /** Reason why matching stopped (for diagnostics) */
    stopReason: "matched" | "multiple_candidates" | "not_found" | "similarity_too_low";
}
/**
 * Edit instruction for a single edit operation.
 */
export interface EditInstruction {
    oldString: string;
    newString: string;
    beforeAnchor?: string;
    afterAnchor?: string;
}
/**
 * Performs exact string matching to find all occurrences.
 */
export declare function matchExact(content: string, needle: string): MatchOutcome;
/**
 * Matches candidates after applying a normalization function.
 */
export declare function matchNormalizedWindows(windows: MatchCandidate[], oldString: string, normalizer: (value: string) => string): MatchOutcome;
/**
 * Performs fuzzy matching using Dice coefficient similarity.
 * Returns match if exactly one candidate exceeds the threshold.
 */
export declare function matchFuzzyWindows(windows: MatchCandidate[], oldString: string, threshold: number): MatchOutcome;
/**
 * Performs fuzzy matching constrained to a region defined by beforeAnchor and afterAnchor.
 * If anchors are not provided, returns not_found.
 */
export declare function matchAnchoredFuzzy(content: string, request: EditInstruction, threshold: number): MatchOutcome;
/**
 * Converts a list of match candidates to a MatchOutcome.
 */
export declare function toExactOutcome(candidates: MatchCandidate[]): MatchOutcome;
/**
 * Finds all occurrences of a string in content.
 * Returns array of MatchCandidate with byte offsets.
 */
export declare function findAllOccurrences(content: string, needle: string): MatchCandidate[];
/**
 * Builds a set of candidate windows (substrings) from content
 * that could potentially match oldString.
 *
 * Windows are generated by sliding across lines with varying spans
 * (number of lines) to account for whitespace/indentation differences.
 */
export declare function buildCandidateWindows(content: string, oldString: string, options?: {
    minSpan?: number;
    maxSpan?: number;
}): MatchCandidate[];
/**
 * Removes duplicate windows that have the same start and end offsets.
 */
export declare function dedupeWindows(windows: MatchCandidate[]): MatchCandidate[];
/**
 * Computes the byte offset for the start of each line in content.
 * Returns array where index is line number (0-based) and value is byte offset.
 */
export declare function computeLineOffsets(content: string): number[];
/**
 * Converts a byte offset to line and column coordinates (1-indexed).
 */
export declare function offsetToLineColumn(content: string, offset: number): {
    line: number;
    column: number;
};
