import type { PlatformId } from "@aa/shared-types";
import { DefaultPlatformAdapter, type PlatformAdapterFactoryOptions } from "./base-platform-adapter.js";
import { MobilePlatformAdapter } from "./mobile-platform-adapter.js";
import { WebPlatformAdapter } from "./web-platform-adapter.js";
export type { PlatformAdapterFactoryOptions } from "./base-platform-adapter.js";
export { DefaultPlatformAdapter, createPlatformAdapterCapabilityView } from "./base-platform-adapter.js";
export type { ElectronBridge, MobileBridge, ShellResult, SpawnedProcessHandle, TauriBridge } from "./bridge-types.js";
export { ElectronPlatformAdapter, DesktopPlatformAdapter, TauriPlatformAdapter } from "./desktop-platform-adapter.js";
export { MobilePlatformAdapter } from "./mobile-platform-adapter.js";
export { PlatformAdapterProvider, usePlatformAdapter } from "./provider.js";
export { WebPlatformAdapter } from "./web-platform-adapter.js";
export declare function createPlatformAdapter(options: PlatformAdapterFactoryOptions): DefaultPlatformAdapter;
export declare function createWebPlatformAdapter(): WebPlatformAdapter;
export declare function createDesktopPlatformAdapter(platform: Extract<PlatformId, "windows" | "macos" | "linux">): DefaultPlatformAdapter;
export declare function createMobilePlatformAdapter(platform: Extract<PlatformId, "android" | "ios">): MobilePlatformAdapter;
