import type { AsyncSqlConnection, AsyncSqlDatabase } from "./async-sql-database.js";
import { AsyncApprovalRepository, AsyncArtifactRepository, AsyncBillingRepository, AsyncCostManagementRepository, AsyncDelegationRepository, AsyncDispatchRepository, AsyncDivisionRepository, AsyncEventRepository, AsyncEvolutionRepository, AsyncExecutionRepository, AsyncIntelligenceRepository, AsyncLeaseRepository, AsyncLockRepository, AsyncMarketplaceListingRepository, AsyncMarketplaceRepository, AsyncMemoryRepository, AsyncOperationsRepository, AsyncOrganizationRepository, AsyncPromptRepository, AsyncReleaseRepository, AsyncSecretRepository, AsyncSessionRepository, AsyncTaskRepository, AsyncTenantRepository, AsyncWorkerRepository, AsyncWorkflowRepository } from "./async-repositories/index.js";
export interface AsyncRepositoryRegistry {
    readonly approval: AsyncApprovalRepository;
    readonly artifact: AsyncArtifactRepository;
    readonly billing: AsyncBillingRepository;
    readonly costManagement: AsyncCostManagementRepository;
    readonly delegation: AsyncDelegationRepository;
    readonly dispatch: AsyncDispatchRepository;
    readonly division: AsyncDivisionRepository;
    readonly event: AsyncEventRepository;
    readonly evolution: AsyncEvolutionRepository;
    readonly execution: AsyncExecutionRepository;
    readonly intelligence: AsyncIntelligenceRepository;
    readonly lease: AsyncLeaseRepository;
    readonly lock: AsyncLockRepository;
    readonly marketplace: AsyncMarketplaceRepository;
    readonly marketplaceListing: AsyncMarketplaceListingRepository;
    readonly memory: AsyncMemoryRepository;
    readonly operations: AsyncOperationsRepository;
    readonly organization: AsyncOrganizationRepository;
    readonly prompt: AsyncPromptRepository;
    readonly release: AsyncReleaseRepository;
    readonly secret: AsyncSecretRepository;
    readonly session: AsyncSessionRepository;
    readonly task: AsyncTaskRepository;
    readonly tenant: AsyncTenantRepository;
    readonly worker: AsyncWorkerRepository;
    readonly workflow: AsyncWorkflowRepository;
}
export declare function createAsyncRepositoryRegistry(target: AsyncSqlDatabase | AsyncSqlConnection): AsyncRepositoryRegistry;
