import type { DomainGovernancePolicy } from "./governance/domain-governance-policy.js";
import type { DomainRiskLevel } from "./risk-profile/index.js";
import type {
  DomainLatencyProfile,
  DomainOwnershipProfile,
  LegacyVerticalDomainId,
  VerticalDomainId,
  VerticalDomainPhase,
} from "./domain-baseline-catalog.js";

export interface DomainSeed {
  readonly phase: VerticalDomainPhase;
  readonly domainId: VerticalDomainId;
  readonly legacyDomainIds: readonly LegacyVerticalDomainId[];
  readonly displayName: string;
  readonly description: string;
  readonly riskLevel: DomainRiskLevel;
  readonly ownerOrgNodeId: string;
  readonly taskTypes: readonly string[];
  readonly tags: readonly string[];
  readonly workflowStages: readonly string[];
  readonly requiredTools: readonly string[];
  readonly optionalTools: readonly string[];
  readonly externalAdapters: readonly string[];
  readonly blockingMetrics: readonly string[];
  readonly advisoryMetrics: readonly string[];
  readonly latencyProfile: DomainLatencyProfile;
  readonly ownershipProfile: Omit<DomainOwnershipProfile, "configPath">;
  readonly rolloutStrategy: DomainGovernancePolicy["rollout"]["strategy"];
  readonly restrictedDataClasses: readonly string[];
}

/**
 * Freezes the array properties of a DomainSeed to ensure they are truly readonly at runtime.
 */
function freezeSeedArrays(seed: DomainSeed): DomainSeed {
  return Object.freeze({
    ...seed,
    legacyDomainIds: Object.freeze([...seed.legacyDomainIds]),
    taskTypes: Object.freeze([...seed.taskTypes]),
    tags: Object.freeze([...seed.tags]),
    workflowStages: Object.freeze([...seed.workflowStages]),
    requiredTools: Object.freeze([...seed.requiredTools]),
    optionalTools: Object.freeze([...seed.optionalTools]),
    externalAdapters: Object.freeze([...seed.externalAdapters]),
    blockingMetrics: Object.freeze([...seed.blockingMetrics]),
    advisoryMetrics: Object.freeze([...seed.advisoryMetrics]),
    restrictedDataClasses: Object.freeze([...seed.restrictedDataClasses]),
  });
}

export const DOMAIN_SEEDS: readonly DomainSeed[] = [
  {
    phase: "9a",
    domainId: "coding",
    legacyDomainIds: [],
    displayName: "Coding",
    description: "Software change delivery and code lifecycle execution.",
    riskLevel: "high",
    ownerOrgNodeId: "org.eng",
    taskTypes: ["analyze", "implement", "test"],
    tags: ["engineering", "code"],
    workflowStages: ["scope_change", "implement_patch", "run_validation", "prepare_release_notes"],
    requiredTools: ["repo_map", "patch_apply", "test_runner"],
    optionalTools: ["static_analysis", "dependency_graph"],
    externalAdapters: ["github", "ci"],
    blockingMetrics: ["quality", "regression_rate"],
    advisoryMetrics: ["latency", "cost"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 15, maxResponseMinutes: 120, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "engineering-ops", ownerTeam: "eng-platform", escalationTeam: "eng-release" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9a",
    domainId: "data-engineering",
    legacyDomainIds: ["data-processing"],
    displayName: "Data Engineering",
    description: "Structured ingestion, transformation, and governed dataset delivery.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.data",
    taskTypes: ["ingest", "clean", "transform"],
    tags: ["data", "etl"],
    workflowStages: ["profile_source", "transform_dataset", "validate_lineage", "publish_dataset"],
    requiredTools: ["schema_registry", "pipeline_runner", "lineage_tracker"],
    optionalTools: ["quality_monitor", "warehouse_query"],
    externalAdapters: ["warehouse", "object-storage"],
    blockingMetrics: ["data_freshness", "schema_validity"],
    advisoryMetrics: ["cost", "throughput"],
    latencyProfile: { tier: "business_day", targetResponseMinutes: 240, maxResponseMinutes: 1440, dataSensitivity: "internal" },
    ownershipProfile: { divisionId: "data", ownerTeam: "data-platform", escalationTeam: "data-governance" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: [],
  },
  {
    phase: "9a",
    domainId: "knowledge-base",
    legacyDomainIds: ["enterprise-knowledge-base"],
    displayName: "Knowledge Base",
    description: "Enterprise documentation, retrieval, and curated knowledge delivery.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.knowledge",
    taskTypes: ["ingest", "search", "curate"],
    tags: ["knowledge", "retrieval"],
    workflowStages: ["collect_sources", "normalize_documents", "index_chunks", "publish_answers"],
    requiredTools: ["document_ingest", "retrieval_index", "citation_builder"],
    optionalTools: ["taxonomy_mapper", "quality_monitor"],
    externalAdapters: ["notion", "wiki"],
    blockingMetrics: ["citation_coverage", "freshness"],
    advisoryMetrics: ["answer_latency", "cost"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 20, maxResponseMinutes: 240, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "research", ownerTeam: "knowledge-ops", escalationTeam: "knowledge-governance" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9a",
    domainId: "user-operations",
    legacyDomainIds: [],
    displayName: "User Operations",
    description: "Lifecycle operations for user cohorts and growth execution.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.growth",
    taskTypes: ["segment", "operate", "follow-up"],
    tags: ["growth", "ops"],
    workflowStages: ["segment_users", "compose_campaign", "schedule_touchpoints", "measure_lift"],
    requiredTools: ["crm_sync", "segment_builder", "journey_scheduler"],
    optionalTools: ["experiment_tracker", "content_generator"],
    externalAdapters: ["crm", "messaging"],
    blockingMetrics: ["opt_in_compliance", "delivery_success"],
    advisoryMetrics: ["conversion_lift", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 30, maxResponseMinutes: 480, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "support", ownerTeam: "growth-ops", escalationTeam: "growth-risk" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9b",
    domainId: "quant-trading",
    legacyDomainIds: ["quantitative-trading"],
    displayName: "Quant Trading",
    description: "Quant strategy research, simulation, and guarded order automation.",
    riskLevel: "critical",
    ownerOrgNodeId: "org.trading",
    taskTypes: ["research", "simulate", "trade"],
    tags: ["trading", "finance"],
    workflowStages: ["ingest_market_data", "run_strategy_backtest", "check_risk_limits", "prepare_order_ticket"],
    requiredTools: ["market_data", "strategy_backtester", "risk_calculator", "order_execution"],
    optionalTools: ["portfolio_analyzer", "trade_journal"],
    externalAdapters: ["exchange", "market-data-feed"],
    blockingMetrics: ["sharpe_ratio", "max_drawdown", "pre_trade_risk"],
    advisoryMetrics: ["fill_rate", "latency"],
    latencyProfile: { tier: "ultra_realtime", targetResponseMinutes: 1, maxResponseMinutes: 5, dataSensitivity: "regulated" },
    ownershipProfile: { divisionId: "analytics", ownerTeam: "quant-research", escalationTeam: "trading-risk" },
    rolloutStrategy: "shadow",
    restrictedDataClasses: ["regulated", "sensitive"],
  },
  {
    phase: "9b",
    domainId: "financial-services",
    legacyDomainIds: [],
    displayName: "Financial Services",
    description: "Customer-facing and regulated financial service workflows.",
    riskLevel: "critical",
    ownerOrgNodeId: "org.finserv",
    taskTypes: ["review", "advise", "execute"],
    tags: ["finance", "regulated"],
    workflowStages: ["collect_customer_context", "perform_policy_checks", "prepare_advice_packet", "route_for_approval"],
    requiredTools: ["policy_checker", "case_manager", "decision_trace"],
    optionalTools: ["kyc_lookup", "pricing_engine"],
    externalAdapters: ["core-banking", "crm"],
    blockingMetrics: ["policy_compliance", "suitability"],
    advisoryMetrics: ["sla_breach_rate", "cost"],
    latencyProfile: { tier: "realtime", targetResponseMinutes: 10, maxResponseMinutes: 60, dataSensitivity: "regulated" },
    ownershipProfile: { divisionId: "security", ownerTeam: "finserv-ops", escalationTeam: "compliance-office" },
    rolloutStrategy: "shadow",
    restrictedDataClasses: ["regulated", "sensitive"],
  },
  {
    phase: "9b",
    domainId: "ecommerce",
    legacyDomainIds: [],
    displayName: "Ecommerce",
    description: "Catalog, order, and merchandising operations.",
    riskLevel: "high",
    ownerOrgNodeId: "org.commerce",
    taskTypes: ["catalog", "pricing", "order"],
    tags: ["commerce", "retail"],
    workflowStages: ["sync_catalog", "optimize_merchandising", "validate_promotions", "publish_changes"],
    requiredTools: ["catalog_admin", "pricing_engine", "inventory_snapshot"],
    optionalTools: ["recommendation_tuner", "promotion_simulator"],
    externalAdapters: ["shop", "payments"],
    blockingMetrics: ["margin_guard", "inventory_accuracy"],
    advisoryMetrics: ["conversion", "latency"],
    latencyProfile: { tier: "realtime", targetResponseMinutes: 10, maxResponseMinutes: 90, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "analytics", ownerTeam: "commerce-ops", escalationTeam: "commerce-risk" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9b",
    domainId: "advertising",
    legacyDomainIds: ["advertising-promotion"],
    displayName: "Advertising",
    description: "Campaign planning, audience targeting, and budget governance.",
    riskLevel: "high",
    ownerOrgNodeId: "org.ads",
    taskTypes: ["plan", "launch", "optimize"],
    tags: ["ads", "campaign"],
    workflowStages: ["plan_campaign", "validate_budget", "activate_channels", "optimize_spend"],
    requiredTools: ["audience_builder", "budget_guard", "channel_launcher"],
    optionalTools: ["creative_brief", "attribution_dashboard"],
    externalAdapters: ["ad-network", "analytics"],
    blockingMetrics: ["budget_adherence", "policy_safety"],
    advisoryMetrics: ["roas", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 20, maxResponseMinutes: 240, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "content", ownerTeam: "ads-ops", escalationTeam: "ads-governance" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9c",
    domainId: "industry-research",
    legacyDomainIds: [],
    displayName: "Industry Research",
    description: "Structured market and industry analysis workflows.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.strategy",
    taskTypes: ["research", "summarize", "brief"],
    tags: ["research", "industry"],
    workflowStages: ["collect_sources", "extract_signals", "compare_competitors", "publish_brief"],
    requiredTools: ["source_collector", "signal_extractor", "brief_builder"],
    optionalTools: ["citation_builder", "trend_scanner"],
    externalAdapters: ["web-research", "knowledge-base"],
    blockingMetrics: ["source_relevance", "citation_coverage"],
    advisoryMetrics: ["freshness", "latency"],
    latencyProfile: { tier: "business_day", targetResponseMinutes: 180, maxResponseMinutes: 1440, dataSensitivity: "internal" },
    ownershipProfile: { divisionId: "research", ownerTeam: "strategy-research", escalationTeam: "strategy-leads" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: [],
  },
  {
    phase: "9c",
    domainId: "academic-research",
    legacyDomainIds: [],
    displayName: "Academic Research",
    description: "Literature collection, evaluation, and synthesis pipelines.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.research",
    taskTypes: ["collect", "evaluate", "synthesize"],
    tags: ["research", "academic"],
    workflowStages: ["collect_papers", "screen_relevance", "summarize_findings", "prepare_citations"],
    requiredTools: ["paper_search", "citation_builder", "evidence_matrix"],
    optionalTools: ["trend_scanner", "knowledge_graph"],
    externalAdapters: ["scholar", "library"],
    blockingMetrics: ["citation_accuracy", "coverage"],
    advisoryMetrics: ["novelty", "latency"],
    latencyProfile: { tier: "business_day", targetResponseMinutes: 240, maxResponseMinutes: 1440, dataSensitivity: "internal" },
    ownershipProfile: { divisionId: "research", ownerTeam: "academic-programs", escalationTeam: "research-governance" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: [],
  },
  {
    phase: "9c",
    domainId: "product-management",
    legacyDomainIds: [],
    displayName: "Product Management",
    description: "Product discovery, roadmap shaping, requirements synthesis, and release coordination.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.product",
    taskTypes: ["discover", "prioritize", "specify"],
    tags: ["product", "roadmap"],
    workflowStages: ["collect_signals", "define_requirements", "prioritize_scope", "prepare_release_brief"],
    requiredTools: ["roadmap_planner", "requirements_editor", "feedback_synthesizer"],
    optionalTools: ["experiment_tracker", "release_calendar"],
    externalAdapters: ["productboard", "issue-tracker"],
    blockingMetrics: ["requirement_quality", "roadmap_alignment"],
    advisoryMetrics: ["cycle_time", "stakeholder_satisfaction"],
    latencyProfile: { tier: "business_day", targetResponseMinutes: 120, maxResponseMinutes: 1440, dataSensitivity: "internal" },
    ownershipProfile: { divisionId: "general-ops", ownerTeam: "product-ops", escalationTeam: "product-leadership" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: [],
  },
  {
    phase: "9c",
    domainId: "quality-assurance",
    legacyDomainIds: [],
    displayName: "Quality Assurance",
    description: "Validation planning, regression oversight, and release quality certification.",
    riskLevel: "high",
    ownerOrgNodeId: "org.qa",
    taskTypes: ["design", "validate", "certify"],
    tags: ["qa", "testing"],
    workflowStages: ["derive_test_plan", "execute_regression", "triage_failures", "certify_release"],
    requiredTools: ["test_manager", "regression_runner", "defect_tracker"],
    optionalTools: ["coverage_analyzer", "performance_profiler"],
    externalAdapters: ["ci", "test-rail"],
    blockingMetrics: ["regression_rate", "quality_gate"],
    advisoryMetrics: ["coverage", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 45, maxResponseMinutes: 480, dataSensitivity: "internal" },
    ownershipProfile: { divisionId: "engineering-ops", ownerTeam: "qa-platform", escalationTeam: "release-quality" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9c",
    domainId: "finance-accounting",
    legacyDomainIds: ["finance"],
    displayName: "Finance Accounting",
    description: "Internal finance operations, reporting, and close workflows.",
    riskLevel: "high",
    ownerOrgNodeId: "org.finance",
    taskTypes: ["reconcile", "report", "forecast"],
    tags: ["finance", "accounting"],
    workflowStages: ["collect_ledgers", "reconcile_variances", "prepare_close_pack", "route_for_signoff"],
    requiredTools: ["ledger_reader", "variance_checker", "close_calendar"],
    optionalTools: ["forecast_model", "approval_router"],
    externalAdapters: ["erp", "spreadsheet"],
    blockingMetrics: ["reconciliation_accuracy", "approval_completeness"],
    advisoryMetrics: ["forecast_delta", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 60, maxResponseMinutes: 720, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "analytics", ownerTeam: "finance-ops", escalationTeam: "controller-office" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9c",
    domainId: "legal",
    legacyDomainIds: [],
    displayName: "Legal",
    description: "Contract review, policy mapping, and legal operations support.",
    riskLevel: "critical",
    ownerOrgNodeId: "org.legal",
    taskTypes: ["review", "redline", "advise"],
    tags: ["legal", "contracts"],
    workflowStages: ["collect_authorities", "review_clause_set", "draft_redlines", "prepare_approval_packet"],
    requiredTools: ["clause_library", "redline_editor", "approval_router"],
    optionalTools: ["matter_tracker", "policy_linker"],
    externalAdapters: ["clm", "dms"],
    blockingMetrics: ["policy_alignment", "approval_completeness"],
    advisoryMetrics: ["turnaround_time", "cost"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 45, maxResponseMinutes: 720, dataSensitivity: "regulated" },
    ownershipProfile: { divisionId: "security", ownerTeam: "legal-ops", escalationTeam: "general-counsel-office" },
    rolloutStrategy: "shadow",
    restrictedDataClasses: ["regulated", "sensitive"],
  },
  {
    phase: "9d",
    domainId: "customer-service",
    legacyDomainIds: [],
    displayName: "Customer Service",
    description: "Customer support triage, response generation, and escalation.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.support",
    taskTypes: ["triage", "respond", "escalate"],
    tags: ["support", "service"],
    workflowStages: ["triage_ticket", "retrieve_context", "draft_response", "escalate_if_needed"],
    requiredTools: ["ticket_router", "knowledge_search", "response_drafter"],
    optionalTools: ["sentiment_monitor", "crm_sync"],
    externalAdapters: ["crm", "support-desk"],
    blockingMetrics: ["csat_proxy", "policy_safety"],
    advisoryMetrics: ["first_response_time", "latency"],
    latencyProfile: { tier: "realtime", targetResponseMinutes: 5, maxResponseMinutes: 30, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "support", ownerTeam: "support-ops", escalationTeam: "customer-experience" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9d",
    domainId: "it-operations",
    legacyDomainIds: [],
    displayName: "IT Operations",
    description: "IT operations, incident handling, and runbook execution.",
    riskLevel: "high",
    ownerOrgNodeId: "org.itops",
    taskTypes: ["detect", "mitigate", "recover"],
    tags: ["itops", "incident"],
    workflowStages: ["detect_incident", "diagnose_signal", "apply_runbook", "verify_recovery"],
    requiredTools: ["incident_feed", "runbook_executor", "system_observer"],
    optionalTools: ["change_freezer", "status_publisher"],
    externalAdapters: ["pager", "monitoring"],
    blockingMetrics: ["incident_containment", "recovery_success"],
    advisoryMetrics: ["mttr", "latency"],
    latencyProfile: { tier: "realtime", targetResponseMinutes: 3, maxResponseMinutes: 30, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "operations", ownerTeam: "it-sre", escalationTeam: "incident-command" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9d",
    domainId: "content-moderation",
    legacyDomainIds: [],
    displayName: "Content Moderation",
    description: "Policy-based moderation and escalation workflows.",
    riskLevel: "high",
    ownerOrgNodeId: "org.safety",
    taskTypes: ["classify", "moderate", "escalate"],
    tags: ["moderation", "safety"],
    workflowStages: ["classify_content", "apply_policy", "queue_for_review", "record_enforcement"],
    requiredTools: ["policy_engine", "content_classifier", "evidence_logger"],
    optionalTools: ["appeal_router", "trend_monitor"],
    externalAdapters: ["ugc-platform", "case-management"],
    blockingMetrics: ["policy_precision", "appeal_reversal_rate"],
    advisoryMetrics: ["queue_latency", "cost"],
    latencyProfile: { tier: "realtime", targetResponseMinutes: 5, maxResponseMinutes: 60, dataSensitivity: "regulated" },
    ownershipProfile: { divisionId: "security", ownerTeam: "trust-safety", escalationTeam: "policy-ops" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["sensitive"],
  },
  {
    phase: "9d",
    domainId: "live-streaming",
    legacyDomainIds: ["online-livestream"],
    displayName: "Live Streaming",
    description: "Livestream planning, moderation, and incident response.",
    riskLevel: "high",
    ownerOrgNodeId: "org.live",
    taskTypes: ["prepare", "moderate", "respond"],
    tags: ["livestream", "ops"],
    workflowStages: ["prepare_show", "monitor_stream", "moderate_events", "stabilize_incidents"],
    requiredTools: ["stream_monitor", "chat_moderator", "incident_feed"],
    optionalTools: ["cue_sheet", "clip_router"],
    externalAdapters: ["stream-platform", "chat-platform"],
    blockingMetrics: ["stream_health", "policy_enforcement"],
    advisoryMetrics: ["viewer_retention", "latency"],
    latencyProfile: { tier: "realtime", targetResponseMinutes: 2, maxResponseMinutes: 15, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "support", ownerTeam: "live-ops", escalationTeam: "broadcast-command" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9d",
    domainId: "project-management",
    legacyDomainIds: [],
    displayName: "Project Management",
    description: "Cross-team delivery planning, dependency tracking, and milestone orchestration.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.pm",
    taskTypes: ["plan", "coordinate", "report"],
    tags: ["project", "delivery"],
    workflowStages: ["collect_dependencies", "plan_milestones", "track_execution", "publish_status"],
    requiredTools: ["dependency_tracker", "milestone_planner", "status_reporter"],
    optionalTools: ["risk_register", "resource_forecaster"],
    externalAdapters: ["jira", "calendar"],
    blockingMetrics: ["dependency_integrity", "milestone_adherence"],
    advisoryMetrics: ["burnup", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 30, maxResponseMinutes: 480, dataSensitivity: "internal" },
    ownershipProfile: { divisionId: "operations", ownerTeam: "delivery-ops", escalationTeam: "pm-governance" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: [],
  },
  {
    phase: "9e",
    domainId: "healthcare",
    legacyDomainIds: ["medical-health"],
    displayName: "Healthcare",
    description: "Healthcare workflow assistance under strict governance.",
    riskLevel: "critical",
    ownerOrgNodeId: "org.health",
    taskTypes: ["triage", "summarize", "coordinate"],
    tags: ["health", "regulated"],
    workflowStages: ["collect_clinical_context", "apply_guidelines", "prepare_summary", "route_for_clinician_review"],
    requiredTools: ["ehr_reader", "guideline_mapper", "clinical_summary"],
    optionalTools: ["care_pathway_router", "appointment_sync"],
    externalAdapters: ["ehr", "care-management"],
    blockingMetrics: ["clinical_safety", "guideline_adherence"],
    advisoryMetrics: ["handoff_latency", "cost"],
    latencyProfile: { tier: "realtime", targetResponseMinutes: 10, maxResponseMinutes: 60, dataSensitivity: "regulated" },
    ownershipProfile: { divisionId: "security", ownerTeam: "clinical-ops", escalationTeam: "medical-governance" },
    rolloutStrategy: "shadow",
    restrictedDataClasses: ["regulated", "sensitive"],
  },
  {
    phase: "9e",
    domainId: "human-resources",
    legacyDomainIds: [],
    displayName: "Human Resources",
    description: "Employee lifecycle, policy, and people-ops workflows.",
    riskLevel: "high",
    ownerOrgNodeId: "org.hr",
    taskTypes: ["screen", "review", "coordinate"],
    tags: ["hr", "people"],
    workflowStages: ["collect_people_context", "apply_policy", "prepare_recommendation", "route_for_manager_signoff"],
    requiredTools: ["hris_reader", "policy_checker", "case_manager"],
    optionalTools: ["scheduler", "sentiment_monitor"],
    externalAdapters: ["hris", "ats"],
    blockingMetrics: ["policy_compliance", "privacy_safety"],
    advisoryMetrics: ["cycle_time", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 30, maxResponseMinutes: 480, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "general-ops", ownerTeam: "people-ops", escalationTeam: "hr-governance" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["sensitive"],
  },
  {
    phase: "9e",
    domainId: "facilities",
    legacyDomainIds: [],
    displayName: "Facilities",
    description: "Facility operations, work orders, access logistics, and environment readiness.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.facilities",
    taskTypes: ["dispatch", "inspect", "coordinate"],
    tags: ["facilities", "work-order"],
    workflowStages: ["triage_request", "schedule_work_order", "verify_completion", "close_ticket"],
    requiredTools: ["work_order_console", "asset_directory", "schedule_planner"],
    optionalTools: ["vendor_router", "badge_system"],
    externalAdapters: ["cmms", "calendar"],
    blockingMetrics: ["work_order_sla", "safety_readiness"],
    advisoryMetrics: ["utilization", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 30, maxResponseMinutes: 480, dataSensitivity: "internal" },
    ownershipProfile: { divisionId: "general-ops", ownerTeam: "facilities-ops", escalationTeam: "workplace-services" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9e",
    domainId: "executive-assistant",
    legacyDomainIds: [],
    displayName: "Executive Assistant",
    description: "Executive scheduling, briefing prep, follow-up tracking, and communications support.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.exec",
    taskTypes: ["schedule", "brief", "follow-up"],
    tags: ["executive", "assistant"],
    workflowStages: ["collect_requests", "prepare_brief", "coordinate_calendar", "track_followups"],
    requiredTools: ["calendar_manager", "brief_builder", "followup_tracker"],
    optionalTools: ["travel_coordinator", "crm_sync"],
    externalAdapters: ["calendar", "mail"],
    blockingMetrics: ["brief_accuracy", "scheduling_conflict_rate"],
    advisoryMetrics: ["throughput", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 20, maxResponseMinutes: 240, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "general-ops", ownerTeam: "executive-ops", escalationTeam: "chief-of-staff" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9e",
    domainId: "supply-chain",
    legacyDomainIds: ["supply-chain-logistics"],
    displayName: "Supply Chain",
    description: "Supply planning, logistics coordination, and exception handling.",
    riskLevel: "high",
    ownerOrgNodeId: "org.supply",
    taskTypes: ["plan", "route", "resolve"],
    tags: ["supply", "logistics"],
    workflowStages: ["assess_supply_signal", "replan_inventory", "coordinate_logistics", "resolve_exception"],
    requiredTools: ["inventory_snapshot", "route_optimizer", "supplier_console"],
    optionalTools: ["forecast_model", "alert_manager"],
    externalAdapters: ["erp", "wms"],
    blockingMetrics: ["fill_rate", "exception_clearance"],
    advisoryMetrics: ["otif", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 20, maxResponseMinutes: 240, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "operations", ownerTeam: "supply-control-tower", escalationTeam: "logistics-command" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9e",
    domainId: "education",
    legacyDomainIds: ["education-training"],
    displayName: "Education",
    description: "Learning design, learner support, and training operations.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.education",
    taskTypes: ["design", "coach", "assess"],
    tags: ["education", "training"],
    workflowStages: ["design_curriculum", "assemble_materials", "deliver_guidance", "assess_outcomes"],
    requiredTools: ["curriculum_planner", "content_library", "assessment_builder"],
    optionalTools: ["schedule_sync", "engagement_tracker"],
    externalAdapters: ["lms", "content-repo"],
    blockingMetrics: ["assessment_quality", "content_safety"],
    advisoryMetrics: ["completion_rate", "latency"],
    latencyProfile: { tier: "business_day", targetResponseMinutes: 120, maxResponseMinutes: 1440, dataSensitivity: "internal" },
    ownershipProfile: { divisionId: "general-ops", ownerTeam: "learning-ops", escalationTeam: "learning-governance" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: [],
  },
  {
    phase: "9f",
    domainId: "creative-production",
    legacyDomainIds: ["advertising-creative"],
    displayName: "Creative Production",
    description: "Creative production for ad assets and campaign content.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.creative",
    taskTypes: ["concept", "draft", "iterate"],
    tags: ["creative", "ads"],
    workflowStages: ["collect_brief", "generate_concepts", "review_brand_safety", "package_assets"],
    requiredTools: ["creative_brief", "asset_generator", "brand_checker"],
    optionalTools: ["storyboard_editor", "feedback_tracker"],
    externalAdapters: ["asset-library", "design-suite"],
    blockingMetrics: ["brand_safety", "brief_alignment"],
    advisoryMetrics: ["iteration_count", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 45, maxResponseMinutes: 720, dataSensitivity: "internal" },
    ownershipProfile: { divisionId: "content", ownerTeam: "creative-studio", escalationTeam: "brand-governance" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: [],
  },
  {
    phase: "9f",
    domainId: "game-dev",
    legacyDomainIds: ["game-development"],
    displayName: "Game Dev",
    description: "Game production, content iteration, and build workflows.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.games",
    taskTypes: ["design", "build", "verify"],
    tags: ["games", "development"],
    workflowStages: ["plan_feature", "implement_content", "run_build_validation", "prepare_playtest"],
    requiredTools: ["build_runner", "asset_pipeline", "playtest_tracker"],
    optionalTools: ["performance_profiler", "bug_triage"],
    externalAdapters: ["build-system", "issue-tracker"],
    blockingMetrics: ["build_success", "performance_budget"],
    advisoryMetrics: ["playtest_feedback", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 30, maxResponseMinutes: 480, dataSensitivity: "internal" },
    ownershipProfile: { divisionId: "engineering-ops", ownerTeam: "game-dev-core", escalationTeam: "game-release" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: [],
  },
  {
    phase: "9f",
    domainId: "game-publishing",
    legacyDomainIds: [],
    displayName: "Game Publishing",
    description: "Release packaging, compliance checks, and store readiness.",
    riskLevel: "high",
    ownerOrgNodeId: "org.games",
    taskTypes: ["package", "review", "release"],
    tags: ["games", "publishing"],
    workflowStages: ["assemble_release", "verify_store_requirements", "prepare_submission", "coordinate_launch"],
    requiredTools: ["release_packager", "store_checklist", "submission_router"],
    optionalTools: ["localization_sync", "marketing_handoff"],
    externalAdapters: ["app-store", "console-store"],
    blockingMetrics: ["store_compliance", "release_readiness"],
    advisoryMetrics: ["approval_cycle_time", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 60, maxResponseMinutes: 1440, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "content", ownerTeam: "publishing-ops", escalationTeam: "release-governance" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9f",
    domainId: "manufacturing",
    legacyDomainIds: [],
    displayName: "Manufacturing",
    description: "Production planning, line exception handling, and quality-governed manufacturing workflows.",
    riskLevel: "high",
    ownerOrgNodeId: "org.manufacturing",
    taskTypes: ["plan", "monitor", "correct"],
    tags: ["manufacturing", "production"],
    workflowStages: ["assess_line_state", "plan_production_run", "resolve_quality_exception", "release_batch"],
    requiredTools: ["mes_console", "quality_gate", "inventory_snapshot"],
    optionalTools: ["supplier_console", "maintenance_router"],
    externalAdapters: ["mes", "erp"],
    blockingMetrics: ["quality_yield", "production_readiness"],
    advisoryMetrics: ["throughput", "cost"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 20, maxResponseMinutes: 240, dataSensitivity: "confidential" },
    ownershipProfile: { divisionId: "operations", ownerTeam: "manufacturing-control", escalationTeam: "plant-operations" },
    rolloutStrategy: "canary",
    restrictedDataClasses: ["internal"],
  },
  {
    phase: "9f",
    domainId: "agriculture",
    legacyDomainIds: [],
    displayName: "Agriculture",
    description: "Field operations, crop planning, compliance tracking, and agricultural decision support.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.agriculture",
    taskTypes: ["plan", "monitor", "recommend"],
    tags: ["agriculture", "field-ops"],
    workflowStages: ["collect_field_signals", "assess_compliance", "recommend_actions", "schedule_followup"],
    requiredTools: ["field_monitor", "compliance_mapper", "advisory_builder"],
    optionalTools: ["weather_feed", "supply_router"],
    externalAdapters: ["iot-field", "weather"],
    blockingMetrics: ["compliance_safety", "signal_accuracy"],
    advisoryMetrics: ["yield_forecast", "latency"],
    latencyProfile: { tier: "business_day", targetResponseMinutes: 180, maxResponseMinutes: 1440, dataSensitivity: "regulated" },
    ownershipProfile: { divisionId: "operations", ownerTeam: "agri-ops", escalationTeam: "agri-governance" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: ["regulated"],
  },
  {
    phase: "9f",
    domainId: "marketing",
    legacyDomainIds: ["marketing-brand"],
    displayName: "Marketing",
    description: "Brand marketing planning, execution, and performance analysis.",
    riskLevel: "medium",
    ownerOrgNodeId: "org.marketing",
    taskTypes: ["plan", "publish", "measure"],
    tags: ["marketing", "brand"],
    workflowStages: ["plan_program", "prepare_content", "launch_assets", "measure_performance"],
    requiredTools: ["calendar_planner", "content_router", "measurement_dashboard"],
    optionalTools: ["brief_generator", "attribution_dashboard"],
    externalAdapters: ["cms", "analytics"],
    blockingMetrics: ["brand_consistency", "approval_completeness"],
    advisoryMetrics: ["pipeline_influence", "latency"],
    latencyProfile: { tier: "near_realtime", targetResponseMinutes: 30, maxResponseMinutes: 480, dataSensitivity: "internal" },
    ownershipProfile: { divisionId: "content", ownerTeam: "brand-marketing", escalationTeam: "brand-ops" },
    rolloutStrategy: "supervised_auto",
    restrictedDataClasses: [],
  },
].map((seed) => freezeSeedArrays(seed as DomainSeed));
