environment          = "dev"
aws_region          = "us-east-1"
vpc_cidr            = "10.10.0.0/16"
availability_zones  = ["us-east-1a", "us-east-1b"]
db_instance_class   = "db.t4g.micro"
db_storage_gb       = 10
redis_node_type     = "cache.t4g.micro"
eks_desired_nodes   = 1
eks_min_nodes       = 1
eks_max_nodes       = 2
eks_node_instance_types = ["t3.small"]
