{{- if and .Values.ingress.enabled (eq .Values.rolloutStrategy "canary") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "automatic-agent.fullname" . }}-canary
  labels:
    {{- include "automatic-agent.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: {{ .Values.canary.weight | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "automatic-agent.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
