apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automatic-agent.fullname" . }}-config
  labels:
    {{- include "automatic-agent.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{- if not (regexMatch ".*(SECRET|TOKEN|PASSWORD|KEY).*" $key) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
