{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "automatic-agent.fullname" . }}
  labels:
    {{- include "automatic-agent.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "automatic-agent.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    - from:
        {{- range .Values.networkPolicy.metricsIngressNamespaceSelectors }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml . | nindent 14 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.metricsPort }}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 4317
        - protocol: TCP
          port: 4318
{{- end }}
