{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "automatic-agent.fullname" . }}-data
  labels:
    {{- include "automatic-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  volumeMode: {{ .Values.persistence.volumeMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
