{{- if .Values.monitoring.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "automatic-agent.fullname" . }}
  labels:
    {{- include "automatic-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "automatic-agent.labels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
{{- end }}
