import { AuthoritativeTaskStoreLegacyCompat } from "./authoritative-task-store-legacy-compat.js";
import type { AuthoritativeTaskStoreRepositories } from "./authoritative-task-store-repositories.js";
import { AuthoritativeTaskStoreDelegatingGovernance } from "./authoritative-task-store-delegating-governance.js";
export declare class AuthoritativeTaskStoreDelegatingRuntime extends AuthoritativeTaskStoreDelegatingGovernance {
    insertAnalyticsFactRecord(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["insertAnalyticsFactRecord"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["insertAnalyticsFactRecord"]>;
    listAnalyticsFactRecords(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listAnalyticsFactRecords"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listAnalyticsFactRecords"]>;
    insertArchiveBundleRecord(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["insertArchiveBundleRecord"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["insertArchiveBundleRecord"]>;
    listArchiveBundleRecords(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listArchiveBundleRecords"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listArchiveBundleRecords"]>;
    insertReplayDatasetRecord(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["insertReplayDatasetRecord"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["insertReplayDatasetRecord"]>;
    listReplayDatasetRecords(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listReplayDatasetRecords"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listReplayDatasetRecords"]>;
    upsertDataMovementJobRecord(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["upsertDataMovementJobRecord"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["upsertDataMovementJobRecord"]>;
    getDataMovementJobRecord(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["getDataMovementJobRecord"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["getDataMovementJobRecord"]>;
    listDataMovementJobRecords(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listDataMovementJobRecords"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listDataMovementJobRecords"]>;
    insertPmfValidationReport(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["insertPmfValidationReport"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["insertPmfValidationReport"]>;
    listPmfValidationReports(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listPmfValidationReports"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listPmfValidationReports"]>;
    getLatestPmfValidationReport(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["getLatestPmfValidationReport"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["getLatestPmfValidationReport"]>;
    listTaskBoardItems(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listTaskBoardItems"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listTaskBoardItems"]>;
    listActiveTasksWithoutWorkflow(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listActiveTasksWithoutWorkflow"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listActiveTasksWithoutWorkflow"]>;
    listStaleExecutions(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listStaleExecutions"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listStaleExecutions"]>;
    listRecoverableExecutingRuns(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listRecoverableExecutingRuns"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listRecoverableExecutingRuns"]>;
    listBlockedRunsAwaitingApproval(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listBlockedRunsAwaitingApproval"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listBlockedRunsAwaitingApproval"]>;
    listStaleRuns(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listStaleRuns"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listStaleRuns"]>;
    buildRuntimeRecoveryView(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["buildRuntimeRecoveryView"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["buildRuntimeRecoveryView"]>;
    listOrphanSessions(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listOrphanSessions"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listOrphanSessions"]>;
    listWorkflowTerminalMismatches(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listWorkflowTerminalMismatches"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listWorkflowTerminalMismatches"]>;
    listActiveTasksWithTerminalSessions(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listActiveTasksWithTerminalSessions"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listActiveTasksWithTerminalSessions"]>;
    listActiveExecutionActivity(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listActiveExecutionActivity"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listActiveExecutionActivity"]>;
    listActiveExecutionConflicts(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listActiveExecutionConflicts"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listActiveExecutionConflicts"]>;
    loadTaskSnapshot(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["loadTaskSnapshot"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["loadTaskSnapshot"]>;
    loadExecutionAuthoritativeView(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["loadExecutionAuthoritativeView"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["loadExecutionAuthoritativeView"]>;
    listRuntimeRecoveryRecords(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listRuntimeRecoveryRecords"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listRuntimeRecoveryRecords"]>;
    getExecution(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["getExecution"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["getExecution"]>;
    getExecutionPrecheck(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["getExecutionPrecheck"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["getExecutionPrecheck"]>;
    getDeadLetterByExecutionId(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["getDeadLetterByExecutionId"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["getDeadLetterByExecutionId"]>;
    listDeadLettersByTask(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listDeadLettersByTask"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listDeadLettersByTask"]>;
    getSession(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["getSession"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["getSession"]>;
    selectLatestSessionByTask(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["selectLatestSessionByTask"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["selectLatestSessionByTask"]>;
    getGatewayTarget(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["getGatewayTarget"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["getGatewayTarget"]>;
    listGatewayTargets(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listGatewayTargets"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listGatewayTargets"]>;
    listMessagesBySession(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listMessagesBySession"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listMessagesBySession"]>;
    listExecutionsByStatuses(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listExecutionsByStatuses"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listExecutionsByStatuses"]>;
    listLeaseAudits(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listLeaseAudits"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listLeaseAudits"]>;
    listActiveFileLocksForResource(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listActiveFileLocksForResource"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listActiveFileLocksForResource"]>;
    insertFileLock(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["insertFileLock"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["insertFileLock"]>;
    listExpiredFileLocks(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listExpiredFileLocks"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listExpiredFileLocks"]>;
    listFileLocks(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listFileLocks"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listFileLocks"]>;
    listFileLocksByTask(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["listFileLocksByTask"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["listFileLocksByTask"]>;
    deleteFileLock(...args: Parameters<AuthoritativeTaskStoreLegacyCompat["deleteFileLock"]>): ReturnType<AuthoritativeTaskStoreLegacyCompat["deleteFileLock"]>;
    countActiveExecutionsByTenant(...args: Parameters<AuthoritativeTaskStoreRepositories["billing"]["countActiveExecutionsByTenant"]>): ReturnType<AuthoritativeTaskStoreRepositories["billing"]["countActiveExecutionsByTenant"]>;
    listRecentExecutionsByTenant(...args: Parameters<AuthoritativeTaskStoreRepositories["billing"]["listRecentExecutionsByTenant"]>): ReturnType<AuthoritativeTaskStoreRepositories["billing"]["listRecentExecutionsByTenant"]>;
    countQueuedTasksByTenant(...args: Parameters<AuthoritativeTaskStoreRepositories["billing"]["countQueuedTasksByTenant"]>): ReturnType<AuthoritativeTaskStoreRepositories["billing"]["countQueuedTasksByTenant"]>;
    listQueuedTasksByTenant(...args: Parameters<AuthoritativeTaskStoreRepositories["billing"]["listQueuedTasksByTenant"]>): ReturnType<AuthoritativeTaskStoreRepositories["billing"]["listQueuedTasksByTenant"]>;
    listSessionsByTask(...args: Parameters<AuthoritativeTaskStoreRepositories["session"]["listSessionsByTask"]>): ReturnType<AuthoritativeTaskStoreRepositories["session"]["listSessionsByTask"]>;
    listGatewayTargetsByChannel(...args: Parameters<AuthoritativeTaskStoreRepositories["session"]["listGatewayTargetsByChannel"]>): ReturnType<AuthoritativeTaskStoreRepositories["session"]["listGatewayTargetsByChannel"]>;
}
