export const WORKER_SNAPSHOT_SELECT = `worker_id AS "workerId",
       status,
       placement,
       isolation_level AS "isolationLevel",
       repo_version AS "repoVersion",
       remote_session_status AS "remoteSessionStatus",
       last_acknowledged_stream_offset AS "lastAcknowledgedStreamOffset",
       stream_resume_success_rate AS "streamResumeSuccessRate",
       credential_refresh_success_rate AS "credentialRefreshSuccessRate",
       session_consistency_check_status AS "sessionConsistencyCheckStatus",
       session_consistency_checked_at AS "sessionConsistencyCheckedAt",
       workspace_sync_status AS "workspaceSyncStatus",
       workspace_sync_checked_at AS "workspaceSyncCheckedAt",
       saturation,
       active_lease_count AS "activeLeaseCount",
       mean_startup_latency_ms AS "meanStartupLatencyMs",
       sandbox_success_rate AS "sandboxSuccessRate",
       repo_cache_hit_rate AS "repoCacheHitRate",
       registration_verified_at AS "registrationVerifiedAt",
       registration_challenge_id AS "registrationChallengeId",
       capabilities_json AS "capabilitiesJson",
       running_executions_json AS "runningExecutionsJson",
       max_concurrency AS "maxConcurrency",
       queue_affinity AS "queueAffinity",
       runtime_instance_id AS "runtimeInstanceId",
       restarted_from_runtime_instance_id AS "restartedFromRuntimeInstanceId",
       restart_generation AS "restartGeneration",
       cpu_pct AS "cpuPct",
       memory_mb AS "memoryMb",
       tool_backlog_count AS "toolBacklogCount",
       current_step_id AS "currentStepId",
       last_progress_at AS "lastProgressAt",
       last_heartbeat_at AS "lastHeartbeatAt",
       updated_at AS "updatedAt"`;

export const AGENT_EXECUTION_SELECT = `execution_id AS "executionId",
        task_id AS "taskId",
        agent_id AS "agentId",
        workflow_id AS "workflowId",
        role_id AS "roleId",
        run_kind AS "runKind",
        runtime_instance_id AS "runtimeInstanceId",
        restarted_from_runtime_instance_id AS "restartedFromRuntimeInstanceId",
        restart_generation AS "restartGeneration",
        status,
        plan_json AS "planJson",
        current_step_id AS "currentStepId",
        last_tool_name AS "lastToolName",
        tool_call_count AS "toolCallCount",
        last_decision_json AS "lastDecisionJson",
        last_error_code AS "lastErrorCode",
        retry_count AS "retryCount",
        progress_message AS "progressMessage",
        started_at AS "startedAt",
        created_at AS "createdAt",
        updated_at AS "updatedAt",
        completed_at AS "completedAt"`;

export const AGENT_EXECUTION_SELECT_SCOPED = `a.execution_id AS "executionId",
          a.task_id AS "taskId",
          a.agent_id AS "agentId",
          a.workflow_id AS "workflowId",
          a.role_id AS "roleId",
          a.run_kind AS "runKind",
          a.runtime_instance_id AS "runtimeInstanceId",
          a.restarted_from_runtime_instance_id AS "restartedFromRuntimeInstanceId",
          a.restart_generation AS "restartGeneration",
          a.status,
          a.plan_json AS "planJson",
          a.current_step_id AS "currentStepId",
          a.last_tool_name AS "lastToolName",
          a.tool_call_count AS "toolCallCount",
          a.last_decision_json AS "lastDecisionJson",
          a.last_error_code AS "lastErrorCode",
          a.retry_count AS "retryCount",
          a.progress_message AS "progressMessage",
          a.started_at AS "startedAt",
          a.created_at AS "createdAt",
          a.updated_at AS "updatedAt",
          a.completed_at AS "completedAt"`;

export const REMOTE_LOG_SELECT = `id,
        task_id AS "taskId",
        execution_id AS "executionId",
        worker_id AS "workerId",
        runtime_instance_id AS "runtimeInstanceId",
        level,
        message,
        context_json AS "contextJson",
        created_at AS "createdAt"`;

export const REMOTE_LOG_SELECT_SCOPED = `r.id,
          r.task_id AS "taskId",
          r.execution_id AS "executionId",
          r.worker_id AS "workerId",
          r.runtime_instance_id AS "runtimeInstanceId",
          r.level,
          r.message,
          r.context_json AS "contextJson",
          r.created_at AS "createdAt"`;

export const HEARTBEAT_SNAPSHOT_SELECT = `id,
        execution_id AS "executionId",
        agent_id AS "agentId",
        runtime_instance_id AS "runtimeInstanceId",
        restart_generation AS "restartGeneration",
        status,
        progress_message AS "progressMessage",
        cpu_pct AS "cpuPct",
        memory_mb AS "memoryMb",
        sampled_at AS "sampledAt"`;

export const EXECUTION_TICKET_SELECT = `id,
        execution_id AS "executionId",
        task_id AS "taskId",
        priority,
        queue_name AS "queueName",
        dispatch_target AS "dispatchTarget",
        required_isolation_level AS "requiredIsolationLevel",
        required_repo_version AS "requiredRepoVersion",
        required_capabilities_json AS "requiredCapabilitiesJson",
        dispatch_after AS "dispatchAfter",
        attempt,
        status,
        assigned_worker_id AS "assignedWorkerId",
        lease_id AS "leaseId",
        claimed_at AS "claimedAt",
        consumed_at AS "consumedAt",
        invalidated_at AS "invalidatedAt",
        created_at AS "createdAt",
        updated_at AS "updatedAt"`;

export const EXECUTION_LEASE_SELECT = `id,
        execution_id AS "executionId",
        worker_id AS "workerId",
        attempt,
        fencing_token AS "fencingToken",
        queue_name AS "queueName",
        status,
        leased_at AS "leasedAt",
        expires_at AS "expiresAt",
        last_heartbeat_at AS "lastHeartbeatAt",
        released_at AS "releasedAt",
        reason_code AS "reasonCode"`;
