import type { AgentExecutionRecord, WorkerSnapshotRecord } from "../../../contracts/types/domain.js";
import type { AuthoritativeTaskStore } from "../../../state-evidence/truth/authoritative-task-store.js";
import type { WorkerHandshakeDecision, WorkerRemoteLogInput } from "./execution-worker-handshake-types.js";
export declare function parseJsonArray(value: string): string[];
export declare function mergeExecutionIds(existing: string[], executionId: string): string[];
export declare function toWorkerStatus(snapshot: WorkerSnapshotRecord, runningExecutionIds: string[]): WorkerSnapshotRecord["status"];
export declare function buildAgentExecutionRecord(store: AuthoritativeTaskStore, execution: NonNullable<ReturnType<AuthoritativeTaskStore["getExecution"]>>, occurredAt: string, updates: {
    agentId: string;
    runtimeInstanceId: string | null;
    restartedFromRuntimeInstanceId: string | null;
    restartGeneration: number;
    status: string;
    currentStepId: string | null;
    lastToolName: string | null;
    toolCallCount: number;
    progressMessage: string | null;
    lastErrorCode: string | null;
    startedAt?: string | null;
    completedAt?: string | null;
}): AgentExecutionRecord;
export declare function persistRemoteLogs(store: AuthoritativeTaskStore, taskId: string, executionId: string, traceId: string, workerId: string, runtimeInstanceId: string | null, remoteLogs: WorkerRemoteLogInput[] | undefined, defaultOccurredAt: string): void;
export declare function recordRejectedEvent(store: AuthoritativeTaskStore, eventType: "worker:claim_rejected" | "worker:heartbeat_rejected", taskId: string, executionId: string, occurredAt: string, payload: Record<string, unknown>): void;
export declare function normalizeLeaseReason(reasonCode: string | null): WorkerHandshakeDecision["reasonCode"];
